### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by robbrad** [rennmaus-coder/ninaAPI#3]
Hey this looks amazing!

How exactly do you install this on Nina?

Thanks !!

**Comment by rennmaus-coder** [comment]
Hi,
I need to update the .NET package to .NET 8 to make it compatible with the latest version of NINA. I will try to do that the next few days if I can find some time

**Comment by robbrad** [comment]
That would be amazing. Also I'm looking to contribute here to this project.

I have an observatory and think the ability to control NINA externally makes a lot of sense. 

I use home assistant currently to bring together automations like humidity reduction, heating etc 

Also I use open and close of the roof with automation to check the scope is horizontal

**Comment by rennmaus-coder** [comment]
Actually, it seems like the .NET 7 version is still compatible. You can download it from inside NINA in the Plugins tab (its called "Advanced API" there). Any contributions are of course welcome. 
I updated the plugin to .NET 8, but I didn't publish a new release, since the .NET 7 version is still working as already mentioned.

**Comment by robbrad** [comment]
Thanks @rennmaus-coder - I dont see it in my Nina - are there some pre-steps ?

![image](https://github.com/rennmaus-coder/ninaAPI/assets/6122503/411bd532-e295-40f2-9c00-1b82e3188c58)

**Comment by rennmaus-coder** [comment]
Ah sorry, I forgot to mention that the plugin was always designed for the NINA 3 Version which is currently in beta

**Comment by robbrad** [comment]
AMAZING - works like a dream
