### ISSUE TITLE
documentation more detailed and v2

### ISSUE THREAD

**Issue by windystory** [rennmaus-coder/ninaAPI#5]
Hello, I’m really glad to see the plugin you’ve developed because it signifies the potential for mobile apps to replace computers in the future. I have some questions about the API you developed. Could you please make the development documentation more detailed and complete, including some examples? Also, I noticed that if the action field of the device is written arbitrarily, it always returns true. I hope you can improve this. Thank you very much! Your efforts will definitely help N.I.N.A move toward mobile!

**Comment by rennmaus-coder** [comment]
Updating the documentation actually has been on my To-Do list for a while, so I guess it is finally time to do it! I will address the issue you mentioned about the action field in the next commit

**Comment by windystory** [comment]
Thank you very much!

**Comment by rennmaus-coder** [comment]
I added examples to all the get requests (sample responses) and fixed the issue about the action field. Also I reorganized the Websocket Events. Would you mind taking a look at the documentation to see if it could be enhanced further? I will add request examples to the control NINA wiki page, but probably no response examples since they would be always pretty much the same

**Comment by windystory** [comment]
Thank you for the example you provided! Implementing all the APIs for the NINA project is not an easy task; I believe it is a significant project. In this version, the APIs and examples do feel a bit chaotic, but that’s okay; I can gradually summarize the development. I have already looked over the example you provided, and I think you could extract the basic JSON response format and create a separate explanation for it, making it easier to read and use.

When the response is an object:
```
{
  "Response": {},
  "Error": "",
  "Success": true,
  "Type": "API"
}
```

When the response is a collection:
```
{
  "Response": [],
  "Error": "",
  "Success": true,
  "Type": "API"
}
```
For the other aspects, I need to actually connect to the device and call the APIs to try them out. Thank you very much for your efforts! I think the v2 version of the API is a great idea. Since you already have experience developing the v1 version, the v2 should be even more powerful and robust!

Overall, I believe this is a very meaningful project, and developing it truly benefits deep-sky photography enthusiasts around the world! Thanks again for your contributions!

**Comment by windystory** [comment]
I apologize for bothering you again. I would like to inquire about the device connection aspect in the Control N.I.N.A. section.

For instance, connecting or disconnecting a camera is manageable as long as there is an API available. However, I'm unsure what information should be provided for the Parameter parameters. Furthermore, when I want to connect the camera, I'm uncertain about how to use your API for device switching. It seems that I might need to manually connect in N.I.N.A. first before I can utilize the API to connect the camera, which leaves me feeling a bit confused. I would greatly appreciate any clarification you could provide. Thank you very much!

**Comment by rennmaus-coder** [comment]
You are right, it would be really useful to be able to specify which device to connect to, but as far as I am aware that ist unfortunately not possible since the functionality isn't directly exposed. However, I will ask on the discord channel if it would be possible to add that.
As of now, the api will always connect to whatever device was connected previously, also before connecting it does a rescan to make sure that all devices are actually available, see [here for the camera](https://github.com/rennmaus-coder/ninaAPI/blob/a58801e3bd573d6a7add243f631b15db05f9caca/ninaAPI/WebService/V2/SET/EquipmentControllerV2.cs#L37)

**Comment by rennmaus-coder** [comment]
I was wondering if you could maybe take a Quick Look at the documentation for the v2 version of the api and tell me if there would be anything you would like to see in the documentation or the api itself as a feature. I would really appreciate your help!

**Comment by windystory** [comment]
Thank you once again for your modifications and improvements! It seems we can only look forward to the community opening up the relevant APIs. The documentation for version 2 is very detailed, and it's truly impressive to browse through it! Thank you again for your efforts! ^_^
